Scriptname MilkQUEST_Conditions extends Quest Conditional
Int Property Debug_enabled Auto Conditional
Bool Property MME_BreasfeedingAnimationsCheck Auto Conditional
Bool Property MME_DialogueMilking Auto Conditional
Bool Property MME_SubjectMaid Auto Conditional
Bool Property MME_SubjectSlave Auto Conditional
Float Property MME_SubjectMilk Auto Conditional
Float Property MME_TargetMilk Auto Conditional
